In [5]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr

array([ 1,  5,  2,  9, 10])

In [2]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [7]:
arr = np.array([1,5,2,9,10])
arr.dtype

dtype('int32')

In [8]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [9]:
arr[2] = 2000
arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [10]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [11]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [12]:
arr[2] = 'test'

ValueError: invalid literal for int() with base 10: 'test'

In [7]:
arr = np.float64(arr)
arr

array([ 1.,  5.,  2.,  9., 10.])

In [10]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.int32)
arr
 
arr = np.uint8(arr)
arr

array([146,  74,   0,  24, 255], dtype=uint8)

In [14]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
arr

array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

In [18]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [21]:
arr.ndim

1

In [22]:
nd_arr.ndim

2

In [23]:
arr.size


5

In [24]:
nd_arr.size

9

In [26]:
arr.shape

(5,)

In [27]:
nd_arr.shape

(3, 3)

In [29]:
arr.itemsize

1

In [30]:
nd_arr.itemsize

2

In [31]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [33]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
zeros_3d

(5, 4, 3)


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

In [36]:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [38]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [39]:
arr = np.linspace(1, 2, 10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [40]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [44]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

0.1111111111111111
0.1


In [57]:
a, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step, 2))

0.45


In [58]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [60]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
arr.shape = (4, 2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [63]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
arr = np.arange(8)
arr_new = arr.reshape((2,4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [67]:
arr.shape = (2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [68]:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [69]:
arr = np.arange(3)
print(arr.shape)

arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


In [70]:
arr = np.linspace(1, 2, 6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [71]:
print(arr[2])

1.4


In [72]:
print(arr[2:4])

[1.4 1.6]


In [73]:
print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


In [74]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [75]:
nd_array[1][2]

3.0

In [76]:
nd_array[1, 2]

3.0

In [77]:
nd_array[:2, 2]

array([1., 3.])

In [78]:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [79]:
nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [80]:
nd_array[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [81]:
nd_array[2, :]

array([4. , 4.5, 5. , 5.5])

In [99]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)

print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [100]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())

print(arr)

None
[ 3  4 12 12 15 23 23 45]


In [102]:
data = np.array([4, 9, -4, 3])

In [103]:
roots = np.sqrt(data)
roots

C:\Users\Home\AppData\Local\Temp\ipykernel_14500\3752651322.py:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [104]:
print(type(None))

print(type(np.nan))

type(np.nan)

<class 'NoneType'>
<class 'float'>


float

In [105]:
print(None == None)

print(np.nan == np.nan)

True
False


In [107]:
print(None is None)

print(np.nan is np.nan)

print(np.nan is None)

True
True
False


In [109]:
sum(roots)

nan

In [110]:
np.isnan(roots)

array([False, False,  True, False])

In [111]:
roots[np.isnan(roots)]

array([nan])

In [113]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [114]:
sum(roots)

6.732050807568877