In [1]:
import numpy as np
np.random.rand()

0.7053567908014783

In [2]:
np.random.rand() * 100

23.660437757321628

In [3]:
np.random.rand(5)

array([0.42948742, 0.4367558 , 0.53232379, 0.90358898, 0.04848242])

In [4]:
np.random.rand(2, 3)

array([[0.72188819, 0.1548    , 0.56370418],
       [0.21689226, 0.44079562, 0.99787183]])

In [14]:
np.random.rand(3,4)

array([[0.30480642, 0.40397228, 0.42846882, 0.53105736],
       [0.96541426, 0.78579809, 0.97836928, 0.46599147],
       [0.27830216, 0.21522555, 0.38141394, 0.03388566]])

In [9]:
shape = (3, 4)
np.random.rand(shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [11]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.01464735, 0.09667295, 0.59545149, 0.67988624],
       [0.80695777, 0.87694124, 0.45883647, 0.21309415],
       [0.44474196, 0.54324814, 0.43178703, 0.83834645]])

In [12]:
shape = (2, 3)
np.random.sample(shape)

array([[0.67043722, 0.14108189, 0.83739241],
       [0.09325567, 0.90816351, 0.54684682]])

In [16]:
# uniform(low=0.0, high=1.0, size=None)

In [17]:
np.random.uniform()

0.714099872763906

In [18]:
np.random.uniform(-30, 50)

27.989223904448586

In [19]:
np.random.uniform(0.5, 0.75, size=5)

array([0.5531468 , 0.65039818, 0.70982272, 0.71301945, 0.52039039])

In [20]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[-135.61349157, -881.36560721,  230.40397198],
       [ 442.19639397, -848.56374787,  489.3093438 ]])

In [21]:
# randint(low, high=None, size=None, dtype=int)

In [22]:
np.random.randint(4, size=(2,3))

array([[0, 3, 2],
       [0, 0, 1]])

In [23]:
np.random.randint(6, 12, size=(3,3))

array([[ 7,  8, 11],
       [ 9,  7,  8],
       [ 8,  8,  6]])

In [24]:
arr = np.arange(6)
print(arr)

print(np.random.shuffle(arr))

arr

[0 1 2 3 4 5]
None


array([3, 1, 5, 4, 2, 0])

In [29]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)

print(playlist)

['Deep Purple' 'Pink Floyd' 'The Beatles' 'ACDC']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [30]:
np.random.permutation(10)

array([5, 7, 6, 2, 9, 0, 3, 1, 8, 4])

In [ ]:
# choice(a, size=None, replace=True)

In [31]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Maria' 'Ivan']


In [32]:
choice = np.random.choice(workers, size=10, replace=False)
print(choice)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [33]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[5 3 2 2 4 2 5 2 2 1]


In [34]:
# np.random.seed(<np.uint32>)

In [38]:
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [42]:
np.random.seed(100)
print(np.random.randint(10, size=3))

print(np.random.randint(10, size=3))

print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]
